---
- hosts: helper
  gather_facts: no


  tasks:
  - name: Install needed packages
    yum:
      state: latest
      name: "{{ item }}"
    with_items:
      - nfs-utils
      - rpcbind


  - name: Create mountable dirs
    file:
      path: "{{ item }}"
      state: directory
      mode: 0777
      owner: nfsnobody
      group: nfsnobody
    with_items:
      - /export
      - /export/ocp/
      - /export/ocp/static
      - /export/ocp/static/registry
      - /export/ocp/dynamic



  - name: FIX permissions
    shell: |
      chmod  777 /export/*

  - name: Configure /etc/exports
    copy:
      dest: "/etc/exports"
      content: |
        /export/ocp	*(rw,sync,root_squash)

  - name: Enable nfs-server
    systemd:
      name: nfs-server
      state: restarted
      enabled: True
