---
- hosts: helper
  gather_facts: no


  tasks:
  - name: Install needed packages
    yum:
      name:
        - bind
        - bind-utils
        - vim
        - bash-completion
        - libselinux-python
      state: present

  - name: Write out named file
    template:
      src: templates/named.conf.j2
      dest: /etc/named.conf
    notify:
      - restart bind


  - copy:
      dest: "/usr/local/bin/set-dns-serial.sh"
      mode: '0555'
      content: |
        #!/bin/bash
        dnsserialfile=/usr/local/src/dnsserialXXXX.txt
        zonefile=/var/named/zonefile.db
        if [ -f zonefile ] ; then
        	echo $[ $(grep serial ${zonefile}  | tr -d "\t"" ""\n"  | cut -d';' -f 1) + 1 ] | tee ${dnsserialfile}
        else
        	if [ ! -f ${dnsserialfile} ] || [ ! -s ${dnsserialfile} ]; then
        		echo $(date +%Y%m%d00) | tee ${dnsserialfile}
        	else
        		echo $[ $(< ${dnsserialfile}) + 1 ] | tee ${dnsserialfile}
        	fi
        fi


  - name: Set zone serial number
    shell: "/usr/local/bin/set-dns-serial.sh"
    register: dymanicserialnumber

  - name: Setting serial number as a fact
    set_fact:
      serialnumber: "{{ dymanicserialnumber.stdout }}"

  - name: Write out "{{ helper.dns.domain }}" zone file
    template:
      src: templates/zonefile.j2
      dest: /var/named/zonefile.db
    notify:
      - restart bind

  - name: Write out reverse zone file
    template:
      src: templates/reverse.j2
      dest: /var/named/reverse.db
    notify:
      - restart bind



  - name: Best effort SELinux repair - DNS
    shell: "restorecon -vR /var/named || true"




  - name: Starting services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - named



  - name: Set the local resolv.conf file
    template:
      src: templates/resolv.conf.j2
      dest: /etc/resolv.conf




#  - name: Change dns servers in interface config


  handlers:
  - name: restart bind
    service:
      name: named
      state: restarted
