---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: "nfs-autoprovisioner"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: "nfs-provisioner"
            - name: NFS_SERVER
              value: "1.250.20.2"
            - name: NFS_PATH
              value: "/export/pv-user-pvs"
      volumes:
        - name: nfs-client-root
          nfs:
            server: "1.250.20.2"
            path: "/export/pv-user-pvs"



---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: "nfs-provisioner"
parameters:
  archiveOnDelete: "false"
