# A Heat environment file which can be used to enable a
# a Manila CephFS Native driver backend.
resource_registry:
  OS::TripleO::Services::ManilaApi: /usr/share/openstack-tripleo-heat-templates/docker/services/manila-api.yaml
  OS::TripleO::Services::ManilaScheduler: /usr/share/openstack-tripleo-heat-templates/docker/services/manila-scheduler.yaml
  # Only manila-share is pacemaker managed:
  OS::TripleO::Services::ManilaShare: /usr/share/openstack-tripleo-heat-templates/docker/services/pacemaker/manila-share.yaml
  OS::TripleO::Services::ManilaBackendCephFs: /usr/share/openstack-tripleo-heat-templates/puppet/services/manila-backend-cephfs.yaml


# If ganesha
  # ceph-nfs (ganesha) service is installed and configured by ceph-ansible
  # but it's still managed by pacemaker

  OS::TripleO::Services::CephNfs: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-nfs.yaml



parameter_defaults:
  ManilaCephFSBackendName: cephfs
  ManilaCephFSDriverHandlesShareServers: false
  ManilaCephFSCephFSAuthId: 'manila'
  ManilaCephFSCephFSEnableSnapshots: true

  # manila cephfs driver supports either native cephfs backend - 'CEPHFS'
  # (users mount shares directly from ceph cluster), or nfs-ganesha backend -
  # 'NFS' (users mount shares through nfs-ganesha server)
#  ManilaCephFSCephFSProtocolHelperType: 'CEPHFS'
  ManilaCephFSCephFSProtocolHelperType: 'NFS'
