resource_registry:
  OS::TripleO::Services::OctaviaApi: /usr/share/openstack-tripleo-heat-templates/docker/services/octavia-api.yaml
  OS::TripleO::Services::OctaviaHousekeeping: /usr/share/openstack-tripleo-heat-templates/docker/services/octavia-housekeeping.yaml
  OS::TripleO::Services::OctaviaHealthManager: /usr/share/openstack-tripleo-heat-templates/docker/services/octavia-health-manager.yaml
  OS::TripleO::Services::OctaviaWorker: /usr/share/openstack-tripleo-heat-templates/docker/services/octavia-worker.yaml
  OS::TripleO::Services::OctaviaDeploymentConfig: /usr/share/openstack-tripleo-heat-templates/docker/services/octavia/octavia-deployment-config.yaml

parameter_defaults:
  NeutronServicePlugins: "qos,router,trunk"
  NeutronEnableForceMetadata: true

  OctaviaControlNetwork: 'lb-mgmt-net'
  OctaviaControlSubnet: 'lb-mgmt-subnet'
  OctaviaControlSecurityGroup: 'lb-mgmt-sec-group'
  OctaviaControlSubnetCidr: '172.30.0.0/16'
  OctaviaControlSubnetGateway: '172.30.0.1'
  OctaviaControlSubnetPoolStart: '172.30.0.2'
  OctaviaControlSubnetPoolEnd: '172.30.255.254'

  OctaviaMgmtPortDevName: "o-hm0"

    # This flag enables internal generation of certificates for communication
    # with amphorae. Use OctaviaCaCert, OctaviaCaKey, OctaviaCaKeyPassphrase
    # and OctaviaClient cert to configure secure production environments.
  OctaviaGenerateCerts: true

  OctaviaLoadBalancerTopology: 'ACTIVE_STANDBY'
