# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Enable SSL on OpenStack Public Endpoints
# description: |
#   Use this environment to pass in certificates for SSL deployments.
#   For these values to take effect, one of the tls-endpoints-*.yaml environments
#   must also be used.
parameter_defaults:
  # The content of the SSL certificate (without Key) in PEM format.
  # Type: string
  SSLCertificate: |
    -----BEGIN CERTIFICATE-----
    MIIEKjCCAhKgAwIBAgICEjQwDQYJKoZIhvcNAQELBQAwZDELMAkGA1UEBhMCRVMx
    DjAMBgNVBAgMBVNwYWluMQ8wDQYDVQQHDAZNYWRyaWQxEDAOBgNVBAoMB1JlZCBI
    YXQxIjAgBgkqhkiG9w0BCQEWE2xhcml6bWVuQHJlZGhhdC5jb20wHhcNMTgwODEz
    MTM1MTI3WhcNMjgwODEwMTM1MTI3WjAUMRIwEAYDVQQDDAkxMC4xLjEuMTAwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDrsvuk52MXORYXbitsD+63aCFQ
    y5frkotHhRI2Nk37C4OQrO3V6be0P2iE5sKUY/WAuZ7MlvDFrIjmuNsZbgA/nDRP
    nK543AXBMU41Q6E9GpC4QLxKqFjwYvlj0R1gtG+bbvja9umLkIkOJgVAdsqL8Rog
    D2QqVIizJx8zeIjtq69WN7JPkxkNyw8oQaHQEPd/LZbh6Sq9FM17rIrH5Dj/rhpx
    wCTukOC3xa2c3tqm1ouc1j2eYzfqEJMwP9JR4q3U37iV+Ul5c4ysIwvxaNYyHgMi
    bxJlVcECgHogPeSZ7UAEu+AKlxlf0x2yGMuISWIStu551ZxbY2neInFKwi1rAgMB
    AAGjNjA0MAkGA1UdEwQCMAAwCwYDVR0PBAQDAgXgMBoGA1UdEQQTMBGHBAoBAQqC
    CTEwLjEuMS4xMDANBgkqhkiG9w0BAQsFAAOCAgEANlUEWvv5mEvIn5Z7zpC5DmNL
    KbaAnMIkUsfiO9L4t2sScIFfj22tyZL6pjeZ0+TQpV4E4tnqN0G2aDzi8pvDx+0z
    oKP6Ms0FczjjrQ8l85IEULPNCHmHv/evxEbb+W09vPBcLsD1drJ0JRg9u1/r2ngh
    yu4Ndl2iVzGlRMSVb0T3sV4vdahGO4VVitVGmrPhpdmYY2b+zSKOzTmuXZYCMozN
    0tNiny2C8wZtRBEOA/9tcjwkU0NFZF8xhITLdA66IhkiuuiP18EShm7mcS+s6UiJ
    hjdibcjDuGqicdKnxvC/lDIX31pGKcvHUB8RgT6ApOKWFFY9a7ZUGATI5Fy5PQ6G
    a0DoSz1mEC7oKrfCRfZGhFz7lex/B8RZu4hav7AGQD8I5MKW5f0eIfBH40yuzJW/
    +TrM1fGso7ILfyucFreIK7uKNwX6DLv/8IHK6/QOOurpyM+ZadASl/TcDp7k1K8l
    tp8hWpHjodirayD8+N4EcGatKrFcuYq61DniY0EKdzQWOEthEvhV9ZosX6uJrMfg
    cjUjIBses1nMmxNji1GaFz76DHt0a8ofpdbrAgjDEGEhEctUsO562ni0YlIuGLr/
    HQGG3lyL7YleY9TwBltAuojEXjnZL3mzFdVTcC1GbvlxyoelmsqVeAEZOo0dlaOy
    K8j7UNupKU2yl1brH5M=
    -----END CERTIFICATE-----


  # The content of an SSL intermediate CA certificate in PEM format.
  # Type: string
  SSLIntermediateCertificate: ''

  # The content of the SSL Key in PEM format.
  # Mandatory. This parameter must be set by the user.
  # Type: string
  SSLKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA67L7pOdjFzkWF24rbA/ut2ghUMuX65KLR4USNjZN+wuDkKzt
    1em3tD9ohObClGP1gLmezJbwxayI5rjbGW4AP5w0T5yueNwFwTFONUOhPRqQuEC8
    SqhY8GL5Y9EdYLRvm2742vbpi5CJDiYFQHbKi/EaIA9kKlSIsycfM3iI7auvVjey
    T5MZDcsPKEGh0BD3fy2W4ekqvRTNe6yKx+Q4/64accAk7pDgt8WtnN7aptaLnNY9
    nmM36hCTMD/SUeKt1N+4lflJeXOMrCML8WjWMh4DIm8SZVXBAoB6ID3kme1ABLvg
    CpcZX9MdshjLiEliErbuedWcW2Np3iJxSsItawIDAQABAoIBAEZOfGvjLZa2y5Uv
    oro4Qm/pGs77/BQkAXHTCuyq5DX3aEZWnxdJASg+JdJG91HGQ2wjcm/6slV0st2H
    1KtQObi/wobg6NZaY0kOiRKwWr9cVkDv5nqqnuUN0PBqZ0X6bLRDtO2z61RbR9a1
    lql1BdQalj1r+ef6kVBHYjI7STUDh7/aaj1yRN4omDYQO++XKBI3sTMIyT+J2l/P
    HF4EvjVuAdmizhl47OAt4DiPDCV6CTinP8NriznyOQwveXo0fICe8REaHbOFJXN1
    33FOxl1ajEX+nCNPl7hjHitr4pyj6atj/MpsVcl6jPVZEtvwspayJufcrNdMSW9c
    EMqrbIECgYEA/4S/o9zrQEcKPP0tTEJMRpEkdd4Ps0zQLheaC+WMbfxX2qMeKUe0
    q/hmkdilpcsfVQLrnDIzDlhNoDiV4pzLjIlOuVTbFCwiK219FBX3PQmKEiPkuY5I
    KtqjRfXWWh4Vto/cWw2Hu7pMu2k/Qda8jeED2Sfum5nZX8qofllOPkECgYEA7CSs
    ogHstfoAjQrstTRCwDu7sOWMEdPvX5T6EhLYsz4ofZhvkc/cefskR3W2sIKjmbk/
    Vq3RWA0gXvw20et2ZvX05GHali+RPvq+tNv6UUbXn23+/DEc67UjZn81eij+hICm
    eVdnILQYeCexKY+Pfk9dIYZJ/oRekQPBZRyImKsCgYEA8IYKS3p6rG/y0ERWbpF9
    8XNRCe61gsdMtAadiJNVJHdET9f6XUtVZAgYrTNtgmp5HPH5zXdnnho7QBXj6YRF
    Cw55X3XkH9IHfC+9bLncmMUxBjBpbs3jWwuiZAms8/mb4NT8zW0oFuugrU2+MQCt
    TzTABZtUPX6OI2DGSOFSCMECgYEA20bS5z1SSUj06gOS+lClC0xsZT9CaeubA+6a
    p93IS+kUQEwkjgmuebazYYf1NMKamExkfGC7XEAUJx+c6CD1uXX7CXe0OnHBNfIw
    1FDQiFh4MRs7A4O3j0iMrsjBJ8aZUQEFlPeMU9noPurcn/MnE+suV8sTOrw/8/jA
    xNtSHDECgYEA38U7dEX+E6Mv2x+X27JEwEzoN87BYo/B70+Rrohm/PqsF72wRKZw
    ndOT+kbEFwx0+qGzme8Q/1ZocRO68gqS2ejh43QkCxFKuZMqy5LhXEkpTcbNn6sL
    5AQZRMtYvHDATIQ43XxRVwxZiCYnrFXuIjoB2YLlyIB5bd6jHAddgkY=
    -----END RSA PRIVATE KEY-----




  # ******************************************************
  # Static parameters - these are values that must be
  # included in the environment but should not be changed.
  # ******************************************************
  # The filepath of the certificate as it will be stored in the controller.
  # Type: string
  DeployedSSLCertificatePath: /etc/pki/tls/private/overcloud_endpoint.pem

  # *********************
  # End static parameters
  # *********************
resource_registry:
  OS::TripleO::NodeTLSData: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/tls/tls-cert-inject.yaml
