---
- hosts: helper
  gather_facts: no


  tasks:


  - name: Install needed packages
    yum:
      name:
        - haproxy
      state: present

  - name: Write out haproxy config file
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
      - restart haproxy


  - name: SEBool allow haproxy connect any port
    seboolean:
      name: haproxy_connect_any
      state: yes
      persistent: yes
    notify:
      - restart haproxy


  - name: Starting services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - haproxy



  handlers:
  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
