#!/bin/bash
set -x
# install openstack cli if it's not there


floatingnetwork=$1
FIP=$2



source adminrc


# Create project and user
openstack project create ocpenv
openstack user create --project ocpenv --password redhat ocpuser
openstack role add --user ocpuser --project ocpenv admin
openstack role add --user ocpuser --project admin admin




cp adminrc ocpuserrc
sed -i -- 's/OS_USERNAME=redhat/OS_USERNAME=ocpuser/g' ocpuserrc
sed -i  '/OS_PASSWORD/d' ocpuserrc ;  echo export OS_PASSWORD=redhat >> ocpuserrc
sed -i -- 's/OS_TENANT_NAME=redhat/OS_TENANT_NAME=ocpenv/g' ocpuserrc
sed -i -- 's/OS_PROJECT_NAME=redhat/OS_PROJECT_NAME=ocpenv/g' ocpuserrc
source ocpuserrc



openstack quota set --cores 100 --instances 50 --ram 131072 --floating-ips 50 --secgroups 50 --secgroup-rules 60 ocpenv



# Flavors
openstack flavor create --ram 16384 --disk 25 --vcpus 4 ocp
#openstack flavor create --ram 16384 --disk 25 --vcpus 4 ocp.bootstrap
#openstack flavor create --ram 16384 --disk 25 --vcpus 4 ocp.master
#openstack flavor create --ram 8192 --disk 25 --vcpus 4 ocp.worker





# Networks
# https://bugzilla.redhat.com/show_bug.cgi?id=1765518
## Remember to include  NeutronEnableInternalDNS: true    (neutron::agents::dhcp::dnsmasq_local_resolv: true)   or NeutronDhcpAgentDnsmasqDnsServers with proper DNS servers  in order to give default DNS server to the autogenerated tenant network used during deployment, otherwise bootstrap node won't be able to access internet





# CEPH and Swift
## Remember to add this in you overcloud config:
#  CephConfigOverrides:
#    rgw_swift_account_in_url: 'true'
#    rgw_swift_versioning_enabled: 'true'


#############################################
## YOU NEED TO CHANGE THE URL OF THE ENDPOINTS TO MAKE IT WORK AFTER including   CephConfigOverrides:    rgw_swift_account_in_url: 'true'

# https://bugzilla.redhat.com/show_bug.cgi?id=1709968

# Solved here: https://opendev.org/openstack/tripleo-heat-templates/commit/086238e9110555f8612cb39336e9b553b5353e18?lang=sv-SE

for i in $(openstack endpoint list -f value -c ID -c "Service Name" | grep swift | awk '{print $1}'); do openstack endpoint set $i  --url "$(openstack endpoint show $i -f value -c url | awk -F '/AUTH' '{print $1}')/AUTH_%(project_id)s"      ;done
#############################################


sleep 5

# swiftoperator is not present
#openstack role add --user ocpuser --project ocpenv swiftoperator

openstack object store account set --property Temp-URL-Key=superkey




# CoreOS
#############################################

#https://bugzilla.redhat.com/show_bug.cgi?id=1764856
mv ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.qcow2 ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.qcow2.gz
gunzip ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.qcow2.gz
#####


qemu-img  convert ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.qcow2 ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.raw
openstack image create rhcos --file ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.raw --disk-format raw --container-format bare

rm -rf ~/ocp/artifacts/openshift-images-4.2.0/rhcos-4.2.0-x86_64-openstack.raw



# FIX floating ip
openstack floating ip create  --floating-ip-address $FIP $floatingnetwork
