# An environment which enables instance HA
# Needs to be combined with environments/services-baremetal/puppet-pacemaker.yaml
# or environments/docker-ha.yaml
# The ComputeInstanceHA *and* PacemakerRemote services need to be added
# to your Compute role
resource_registry:
  # FIXME(bogdando): switch it, once it is containerized
  OS::TripleO::Services::ComputeInstanceHA: /usr/share/openstack-tripleo-heat-templates/puppet/services/pacemaker/compute-instanceha.yaml

parameter_defaults:
  EnableInstanceHA: true
