heat_template_version: pike

description: >
  All Pre deployment scripts

parameters:
  server:
    type: string

resources:

  PreDeployScriptConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: pre_deploy_scripts/pre-deploy_script.sh}

  PreDeployScriptDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: PreDeployScriptConfig}
      server: {get_param: server}
      actions: ['CREATE','UPDATE']

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger pre-deploy on changes
    value: {get_attr: [PreDeployScriptDeployment, deploy_stdout]}
